name: Setup
description: Setup for build

runs:
  using: composite
  steps:
    - name: Set the timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: America/Halifax

    - name: Set the Node version
      uses: https://github.com/actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # 4.0.3
      with:
        cache: npm
        node-version-file: ".nvmrc"
