name: Setup
description: Setup for build

runs:
  using: composite
  steps:
    - name: Set the timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: America/Halifax

    - name: Set the Node version
      uses: actions/setup-node@v4
      with:
        cache: npm
        node-version-file: ".nvmrc"
