name: Setup
description: Setup for build

runs:
  using: composite
  steps:
    - name: Set the timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: America/Halifax

    - name: Set the Node version
      uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # 6.1.0
      with:
        cache: npm
        node-version-file: ".nvmrc"
