name: Setup
description: Setup for build

runs:
  using: composite
  steps:
    - name: Set the timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: America/Halifax

    - name: Set the Node version
      uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # 6.2.0
      with:
        cache: npm
        node-version-file: ".nvmrc"
