name: Production

on:
  push:
    branches:
      - main
  schedule:
    # Daily @ 01:00, 07:00, 13:00, 19:00
    - cron: "0 1,7,13,19 * * *"
    # CSS Naked Day, Start @ 8 April 10:00
    - cron: "0 10 8 4 *"
    # CSS Naked Day, End @ 10 April 12:00
    - cron: "0 12 10 4 *"
    # JS Naked Day, Start @ 23 April 10:00
    - cron: "0 10 23 4 *"
    # JS Naked Day, End @ 25 April 12:00
    - cron: "0 12 25 4 *"

concurrency:
  group: production
  cancel-in-progress: ${{ env.FORGEJO_EVENT_NAME != 'schedule' }}

jobs:
  build:
    name: Production
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup
        uses: ./.forgejo/actions/setup

      - name: Install
        uses: ./.forgejo/actions/install

      - name: Test
        uses: ./.forgejo/actions/test

      - name: Restore 11ty cache
        id: restore-eleventy-cache
        uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: .cache
          key: eleventy-cache-${{ env.FORGEJO_RUN_ID }}-${{ env.FORGEJO_RUN_ATTEMPT }}
          restore-keys: |
            eleventy-cache-${{ env.FORGEJO_RUN_ID }}-
            eleventy-cache-

      - name: Restore Site cache
        id: restore-site-cache
        uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: |
            _site
            !_site/og-images
            !_site/pagefind
          key: site-cache-${{ env.FORGEJO_RUN_ID }}
          restore-keys: site-cache-

      - name: Restore OG images cache
        id: restore-og-images-cache
        uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: _site/og-images
          key: og-images-cache-${{ env.FORGEJO_RUN_ID }}
          restore-keys: og-images-cache-

      - name: Build
        if: steps.restore-site-cache.outputs.cache-hit != 'true'
        uses: ./.forgejo/actions/build-production
        env:
          FATHOM_SUMMARY_KEY: ${{ secrets.FATHOM_SUMMARY_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LASTFM_API_TOKEN: ${{ secrets.LASTFM_API_TOKEN }}
          MUSICTHREAD_API_KEY: ${{ secrets.MUSICTHREAD_API_KEY }}
          PERSONAL_API_KEY: ${{ secrets.PERSONAL_API_KEY }}
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          TRAKT_CLIENT_ID: ${{ secrets.TRAKT_CLIENT_ID }}
          VIGENERE_SECRET: ${{ secrets.VIGENERE_SECRET }}
          WEBMENTION_IO_TOKEN: ${{ secrets.WEBMENTION_IO_TOKEN }}

      - name: Check Build
        if: steps.restore-site-cache.outputs.cache-hit != 'true'
        uses: ./.forgejo/actions/check

      - name: Install SSH Key
        uses: https://github.com/shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_KEY }}
          known_hosts: "unnecessary"

      - name: Copy files to server
        run: |
          ssh-keyscan -p ${{ secrets.DEPLOY_PORT }} -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts
          rsync -azh --delete --exclude="audio" --exclude="fonts" --exclude="static" --chown=${{ secrets.DEPLOY_CHOWN }} \
            -e "ssh -p ${{ secrets.DEPLOY_PORT }}" \
            ./_site/ ${{ secrets.DEPLOY_USERNAME }}@${{ secrets.DEPLOY_HOST }}:${{ secrets.DEPLOY_PATH }}html

      - name: Process on server
        uses: https://github.com/appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          port: ${{ secrets.DEPLOY_PORT }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: "${{ secrets.DEPLOY_PATH }}${{ secrets.DEPLOY_FILE }}"

      - name: Save 11ty cache
        id: save-eleventy-cache
        if: always()
        uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: .cache
          key: eleventy-cache-${{ env.FORGEJO_RUN_ID }}-${{ env.FORGEJO_RUN_ATTEMPT }}

      - name: Save Site cache
        id: save-site-cache
        if: steps.restore-site-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: |
            _site
            !_site/og-images
            !_site/pagefind
          key: site-cache-${{ env.FORGEJO_RUN_ID }}

      - name: Save OG images cache
        id: save-og-images-cache
        if: steps.restore-og-images-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: _site/og-images
          key: og-images-cache-${{ env.FORGEJO_RUN_ID }}
