name: Review

on:
  push:
    branches-ignore:
      - "**"
  pull_request:
    branches:
      - main

concurrency:
  group: review

jobs:
  build:
    name: Review
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2

      - name: Setup
        uses: ./.forgejo/actions/setup

      - name: Install
        uses: ./.forgejo/actions/install

      - name: Test
        uses: ./.forgejo/actions/test

      - name: Restore 11ty cache
        id: restore-eleventy-cache
        uses: actions/cache/restore@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # 5.0.3
        with:
          path: .cache
          key: eleventy-cache-${{ env.FORGEJO_RUN_ID }}-${{ env.FORGEJO_RUN_ATTEMPT }}
          restore-keys: |
            eleventy-cache-${{ env.FORGEJO_RUN_ID }}-
            eleventy-cache-

      - name: Restore Site cache
        id: restore-site-cache
        uses: actions/cache/restore@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # 5.0.3
        with:
          path: |
            _site
            !_site/og-images
            !_site/pagefind
          key: site-cache-${{ env.FORGEJO_RUN_ID }}
          restore-keys: site-cache-

      - name: Restore OG images cache
        id: restore-og-images-cache
        uses: actions/cache/restore@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # 5.0.3
        with:
          path: _site/og-images
          key: og-images-cache-${{ env.FORGEJO_RUN_ID }}
          restore-keys: og-images-cache-

      - name: Build
        uses: ./.forgejo/actions/build-production
        env:
          FATHOM_SUMMARY_KEY: ${{ secrets.FATHOM_SUMMARY_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LASTFM_API_TOKEN: ${{ secrets.LASTFM_API_TOKEN }}
          MUSICTHREAD_API_KEY: ${{ secrets.MUSICTHREAD_API_KEY }}
          PERSONAL_API_KEY: ${{ secrets.PERSONAL_API_KEY }}
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          TRAKT_CLIENT_ID: ${{ secrets.TRAKT_CLIENT_ID }}
          VIGENERE_SECRET: ${{ secrets.VIGENERE_SECRET }}
          WEBMENTION_IO_TOKEN: ${{ secrets.WEBMENTION_IO_TOKEN }}

      - name: Check Build
        uses: ./.forgejo/actions/check
