name: Scheduled Deploy

on:
  schedule:
    # https://crontab.guru/#33_1/6_*_*_*
    - cron: "33 1/6 * * *"
    # CSS Naked Day
    - cron: "0 10 8 4 *"
    - cron: "0 12 10 4 *"
    # JS Naked Day
    - cron: "0 10 23 4 *"
    - cron: "0 12 25 4 *"

concurrency:
  group: deploy-live

jobs:
  build:
    name: Scheduled Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: https://github.com/@692973e3d937129bcbf40652eb9f2f61becf3332 # 4.1.7
        with:
          lfs: true

      - name: Setup
        uses: ./.forgejo/actions/setup

      - name: Install
        uses: ./.forgejo/actions/install

      - name: Test
        uses: ./.forgejo/actions/test

      - name: Build
        uses: ./.forgejo/actions/build-for-live
        env:
          NODE_OPTIONS: "--max_old_space_size=8192"
          FATHOM_SUMMARY_KEY: ${{ secrets.FATHOM_SUMMARY_KEY }}
          LASTFM_API_TOKEN: ${{ secrets.LASTFM_API_TOKEN }}
          MUSICTHREAD_API_KEY: ${{ secrets.MUSICTHREAD_API_KEY }}
          PERSONAL_API_KEY: ${{ secrets.PERSONAL_API_KEY }}
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          TRAKT_CLIENT_ID: ${{ secrets.TRAKT_CLIENT_ID }}
          VIGENERE_SECRET: ${{ secrets.VIGENERE_SECRET }}
          WEBMENTION_IO_TOKEN: ${{ secrets.WEBMENTION_IO_TOKEN }}

      - name: Check Build
        uses: ./.forgejo/actions/check

      - name: Install SSH Key
        uses: https://github.com/shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_KEY }}
          known_hosts: "unnecessary"

      - name: Copy files to server
        run: |
          ssh-keyscan -p ${{ secrets.DEPLOY_PORT }} -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts
          rsync -az -e "ssh -p ${{ secrets.DEPLOY_PORT }}" --delete --exclude="audio" --exclude="fonts" --exclude="static" --size-only ./_site/ ${{ secrets.DEPLOY_USERNAME }}@${{ secrets.DEPLOY_HOST }}:${{ secrets.DEPLOY_PATH }}html
          rsync -az -e "ssh -p ${{ secrets.DEPLOY_PORT }}" --delete ./_site/pagefind/ ${{ secrets.DEPLOY_USERNAME }}@${{ secrets.DEPLOY_HOST }}:${{ secrets.DEPLOY_PATH }}html/pagefind/

      - name: Process on server
        uses: https://github.com/appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          port: ${{ secrets.DEPLOY_PORT }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: "${{ secrets.DEPLOY_PATH }}${{ secrets.DEPLOY_FILE }}"
