name: Setup
description: Setup for build

runs:
  using: composite
  steps:
    - name: Set the timezone
      uses: https://github.com/zcong1993/setup-timezone@master
      with:
        timezone: America/Halifax

    - name: Set the Node version
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.3.0
      with:
        cache: npm
        node-version-file: ".nvmrc"
