name: Check
description: Check build for errors

runs:
  using: composite
  steps:
    - name: Check Build Stats
      run: pnpm run check:stats
      shell: bash

    - name: Check DateTimes
      run: pnpm run check:datetimes
      shell: bash
