name: Install
description: Install dependencies

runs:
  using: composite
  steps:
    - name: Install the latest version of npm and pnpm
      run: npm install -g npm@latest pnpm@latest-11
      shell: bash

    - name: Install Node Modules
      run: pnpm ci --include=optional
      shell: bash
