name: Deploy
description: Deploy the site

runs:
  using: composite
  steps:
    - name: Copy files to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        port: ${{ secrets.DEPLOY_PORT }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        key: ${{ secrets.DEPLOY_KEY }}
        rm: true
        source: "_site/*"
        target: "${{ secrets.DEPLOY_PATH }}build"
        strip_components: 1

    - name: Process on server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        port: ${{ secrets.DEPLOY_PORT }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: "${{ secrets.DEPLOY_PATH }}${{ secrets.DEPLOY_FILE }}"
