name: Build
description: Build the site for main

runs:
  using: composite
  steps:
    - name: Build website
      run: |
        set -e
        npm run build:prod
      shell: bash

    - name: Build search index
      run: npm run create-search-index
      shell: bash
