name: Install
description: Install dependencies

runs:
  using: composite
  steps:
    - name: Install Node Modules
      run: npm ci --include=optional
      shell: bash

    - run: npm install --include=optional sharp
      shell: bash

    - run: npm install --include=optional @resvg/resvg-js
      shell: bash

    - run: npm install --include=optional pagefind @pagefind/linux-x64
      shell: bash
