name: Install
description: Install dependencies

runs:
  using: composite
  steps:
    - name: Install Node Modules
      run: npm ci
      shell: bash

    - name: Install Sharp
      run: npm install --include=optional sharp
      shell: bash
