name: Build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # https://crontab.guru/#33_1_*_*_*
    - cron: "33 1 * * *"
    - cron: "33 7 * * *"
    - cron: "33 13 * * *"
    - cron: "33 19 * * *"

concurrency:
  group: build-and-deploy
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set the timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Singapore
      - name: Checkout from git
        uses: actions/checkout@v3
      - name: Set the Node version
        uses: actions/setup-node@v3
        with:
          node-version: "20.11.0"
      - name: Setup npm dependencies cache
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-packages-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-packages-
      - name: Setup site assets cache
        id: cache-site
        uses: actions/cache@v3
        with:
          path: |
            .cache
            _site/images
            _site/og-images
          key: ${{ runner.OS }}-site
          restore-keys: |
            ${{ runner.os }}-site
      - name: Install Node Modules
        run: npm ci
      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list
  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Build with npm
        run: npm run build
        env:
          NODE_OPTIONS: "--max_old_space_size=8192"
          WEBMENTION_IO_TOKEN: ${{ secrets.WEBMENTION_IO_TOKEN }}
  deploy:
    runs-on: ubuntu-latest
    needs: [setup, build]
    steps:
      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          port: ${{ secrets.DEPLOY_PORT }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          rm: true
          source: "_site/*"
          target: "${{ secrets.DEPLOY_PATH }}build"
          strip_components: 1
      - name: Process on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          port: ${{ secrets.DEPLOY_PORT }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: "${{ secrets.DEPLOY_PATH }}${{ secrets.DEPLOY_FILE }}"
