name: Build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # https://crontab.guru/#33_1_*_*_*
    - cron: "33 1 * * *"
    - cron: "33 7 * * *"
    - cron: "33 13 * * *"
    - cron: "33 19 * * *"
    # CSS Naked Day switches
    - cron: "0 10 8 4 *"
    - cron: "0 12 10 4 *"

concurrency:
  group: build-and-deploy
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set the timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Singapore

      - name: Checkout from git
        uses: actions/checkout@v4

      - name: Set the Node version
        uses: actions/setup-node@v4
        with:
          node-version: "20.11.0"
          cache: npm

      - name: Install Node Modules
        run: npm ci

      - name: Set up site cache
        id: cache-site
        uses: actions/cache@v4
        with:
          key: site-cache
          path: |
            .cache
            _site/images
            _site/og-images

      - name: Build with npm
        run: npm run build-production
        env:
          NODE_OPTIONS: "--max_old_space_size=8192"
          DARK_VISITORS_API_TOKEN: ${{ secrets.DARK_VISITORS_API_TOKEN }}
          LASTFM_API_TOKEN: ${{ secrets.LASTFM_API_TOKEN }}
          WEBMENTION_IO_TOKEN: ${{ secrets.WEBMENTION_IO_TOKEN }}

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          port: ${{ secrets.DEPLOY_PORT }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          rm: true
          source: "_site/*"
          target: "${{ secrets.DEPLOY_PATH }}build"
          strip_components: 1

      - name: Process on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          port: ${{ secrets.DEPLOY_PORT }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: "${{ secrets.DEPLOY_PATH }}${{ secrets.DEPLOY_FILE }}"
