name: Production Deploy

on:
  push:
    branches:
      - main
  schedule:
    # https://crontab.guru/#33_1_*_*_*
    - cron: "33 1 * * *"
    - cron: "33 7 * * *"
    - cron: "33 13 * * *"
    - cron: "33 19 * * *"
    # CSS Naked Day switches
    - cron: "0 10 8 4 *"
    - cron: "0 12 10 4 *"

concurrency:
  group: production-deploy
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Install
        uses: ./.github/actions/install
      - name: Build
        uses: ./.github/actions/build
        env:
          NODE_OPTIONS: "--max_old_space_size=8192"
          DARK_VISITORS_API_TOKEN: ${{ secrets.DARK_VISITORS_API_TOKEN }}
          LASTFM_API_TOKEN: ${{ secrets.LASTFM_API_TOKEN }}
          WEBMENTION_IO_TOKEN: ${{ secrets.WEBMENTION_IO_TOKEN }}
      - name: Deploy
        uses: ./.github/actions/deploy
