name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "01 1 * * *"
    - cron: "01 13 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set the timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Europe/London
      - name: Checkout from git
        uses: actions/checkout@v3
      - name: Set the Node version
        uses: actions/setup-node@v1
        with:
          node-version: "19.0.0"
      - name: Setup npm dependencies cache
        id: cache_npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
      - name: Setup Eleventy assets cache
        id: cache_eleventy
        uses: actions/cache@v3
        with:
          path: |
            .cache
            _site/audio
            _site/images
          key: ${{ runner.OS }}-site-cache-${{ hashFiles('**/lockfiles') }}
      - name: Install Node Modules
        run: npm ci
      - name: Build with npm
        run: npm run build
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
          ELEVENTY_PRODUCTION: true
          ODESLI_URL: ${{ secrets.ODESLI_TOKEN }}
          PERSONAL_API_URL: ${{ secrets.PERSONAL_API_URL }}
          PERSONAL_API_TOKEN: ${{ secrets.PERSONAL_API_TOKEN }}
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          WEBMENTION_IO_TOKEN: ${{ secrets.WEBMENTION_IO_TOKEN }}
      - name: Copy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          port: ${{ secrets.DEPLOY_PORT }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          rm: true
          source: "_site/*"
          target: "${{ secrets.DEPLOY_PATH }}build"
          strip_components: 1
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          port: ${{ secrets.DEPLOY_PORT }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: "${{ secrets.DEPLOY_PATH }}${{ secrets.DEPLOY_FILE }}"
